sudo: required

language: java

jdk:
- oraclejdk7

services:
- docker



# run unit tests and build JARs
script:
- ./gradlew clean test
- ./gradlew clean build

# build Docker images and push to Docker Hub
after_success:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker build -f ./Dockerfile_middletier -t "$RSS_MIDDLETIER_IMAGE" .
- docker push "$RSS_MIDDLETIER_IMAGE"
- docker build -f ./Dockerfile_edge -t "$RSS_EDGE_IMAGE" .
- docker push "$RSS_EDGE_IMAGE"
