sudo: required

language: java

jdk:
- oraclejdk7

services:
- docker

env:
  DOCKER_COMPOSE_VERSION: 1.5.1



before_install:
# install given version of Docker Compose
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin

before_script:
# determine tag for Docker images based on current commit
- echo $(if [ -n "$TRAVIS_TAG" ]; then echo $TRAVIS_TAG;elif [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest";else echo $TRAVIS_BRANCH;fi) > tag
# set JAR version
- sed -i -e "s/.*version.*/version=current/" gradle.properties

script:
# run unit tests
- ./gradlew --quiet clean test
# build JARs
- ./gradlew --quiet clean build
# build Docker images
- 'docker build -f Dockerfile_middletier -t "$RSS_MIDDLETIER_IMAGE:$(cat tag)" .'
- 'docker build -f Dockerfile_edge -t "$RSS_EDGE_IMAGE:$(cat tag)" .'
# run integration test
- ./test/smoketest.sh
# push Docker images to Docker Hub
- '$(cat test-result) && docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"'
- '$(cat test-result) && docker push "$RSS_MIDDLETIER_IMAGE:$(cat tag)"'
- '$(cat test-result) && docker push "$RSS_EDGE_IMAGE:$(cat tag)"'

# send out notifications by e-mail, slack, ...
# https://docs.travis-ci.com/user/notifications/
