FROM java:7

MAINTAINER Johannes Wettinger
# based on github.com/hora-prediction/recipes-rss-kube-docker

ENV RSS_VERSION current

ADD rss-middletier/build/libs/rss-middletier-${RSS_VERSION}.jar /opt/netflix-rss/rss-middletier.jar

WORKDIR /opt/netflix-rss

#RUN ./gradlew clean test
#RUN ./gradlew clean build

EXPOSE 9191

CMD [ "java", "-jar", "rss-middletier.jar" ]



#
# ./gradlew clean build
# docker build -f ./Dockerfile_middletier -t netflix-rss-middletier .
# docker run -d -p 9191:9191 netflix-rss-middletier
#
