FROM java:7

MAINTAINER Johannes Wettinger
# based on github.com/hora-prediction/recipes-rss-kube-docker

ADD rss-edge/build/libs/rss-edge-0.1.0-SNAPSHOT.jar /opt/netflix-rss/rss-edge-0.1.0-SNAPSHOT.jar
WORKDIR /opt/netflix-rss

#RUN ./gradlew clean test
#RUN ./gradlew clean build

EXPOSE 9090

CMD [ "java", "-jar", "rss-edge-0.1.0-SNAPSHOT.jar" ]



#
# ./gradlew clean build
# docker build -f ./Dockerfile_edge -t netflix-rss-edge .
# docker run -d -p 9090:9090 netflix-rss-edge
#
