FROM java:7

MAINTAINER Johannes Wettinger
# based on github.com/hora-prediction/recipes-rss-kube-docker

ENV RSS_VERSION current

ADD rss-edge/build/libs/rss-edge-${RSS_VERSION}.jar /opt/netflix-rss/rss-edge.jar

WORKDIR /opt/netflix-rss

#RUN ./gradlew clean test
#RUN ./gradlew clean build

EXPOSE 9090

CMD [ "java", "-jar", "rss-edge.jar" ]



#
# ./gradlew clean build
# docker build -f ./Dockerfile_edge -t netflix-rss-edge .
# docker run -d -p 9090:9090 netflix-rss-edge
#
